CC = gcc
CFLAGS = -O -Wall

all: c26_1 multiple_wait

c26_1: c26_1.c
	$(CC) $(CFLAGS) c26_1.c -o c26_1

multiple_wait: multiple_wait.c
	$(CC) $(CFLAGS) multiple_wait.c -o multiple_wait

clean:
	rm -f *.o npshell *~ c26_1 multiple_wait